name: Deploy to Turing

on:
  push:
    branches:
      - main  # ou a branch que deseja monitorar para implantação

jobs:
  deploy:
    runs-on: ubuntu-latest  # ou a imagem de sistema operacional desejada

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '17'  # ou a versão do Java desejada
      
      - name: 📂 Sync files
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.ftp_host }}
          username: ${{ secrets.ftp_user }}
          password: ${{ secrets.ftp_password }}
          # protocol: ftps
          sftp_only: true
          port: ${{ secrets.ftp_port }}
          remote_path: public_html/greetings/greetingsAPI/target
          
      - name: Build Maven
        run: |
          cd greetingsAPI
          chmod +x mvnw
          ./mvnw clean package
          ls
      
      - name: Replace Jar
        run: |
          ls
      
      - name: Restart Project
        run: |
          ls
      
