name: Deploy to Turing

on:
  push:
    branches:
      - main  # ou a branch que deseja monitorar para implantação

jobs:
  deploy:
    runs-on: ubuntu-latest  # ou a imagem de sistema operacional desejada

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '17'  # ou a versão do Java desejada
      
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.ftp_host }}
          username: ${{ secrets.ftp_user }}
          password: ${{ secrets.ftp_password }}
          protocol: SFTP
          port: 2345
          server-dir: public_html/greetings/greetingsAPI/
          
      - name: Build Maven
        run: |
          chmod +x mvnw
          ./mvnw clean package
          java -jar target/greetingsAPI-0.0.1-SNAPSHOT.jar
          
      
