name: Deploy to Turing

on:
  push:
    branches:
      - main  # ou a branch que deseja monitorar para implantação

jobs:
  deploy:
    runs-on: ubuntu-latest  # ou a imagem de sistema operacional desejada

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '17'  # ou a versão do Java desejada
          
      - name: Build Maven
        run: |
          cd greetingsAPI/
          chmod +x mvnw
          ./mvnw clean package

      - name: Deploy to Turing
        run: |
          scp target/*.jar 2021.1.08.030@www2.bcc.unifal-mg.edu.br:/home/username/public_html/greetings/
